// Vite plugin: after the build is written, emit `sw.js` into the output folder with a precache
// list of every file in the build (hashed JS/CSS/images, index.html, manifest, icons) and a
// version derived from the file contents. All URLs are relative to the worker, so the same build
// works on the GitHub Pages sub-path (https://<user>.github.io/<repo>/) and from any static folder.
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, relative, resolve, sep } from 'node:path';
import type { Plugin, ResolvedConfig } from 'vite';

export const SW_FILENAME = 'sw.js';

/** Files that must never be precached (the worker itself, source maps, OS clutter). */
function isExcluded(rel: string): boolean {
  return rel === SW_FILENAME || rel.endsWith('.map') || rel.endsWith('.DS_Store');
}

/** Every file under `dir`, as sorted POSIX paths relative to `dir`. */
export function listBuildFiles(dir: string): string[] {
  const out: string[] = [];
  const walk = (p: string): void => {
    for (const name of readdirSync(p)) {
      const full = join(p, name);
      if (statSync(full).isDirectory()) walk(full);
      else {
        const rel = relative(dir, full).split(sep).join('/');
        if (!isExcluded(rel)) out.push(rel);
      }
    }
  };
  walk(dir);
  return out.sort();
}

/** Short content hash of the whole build: changes whenever any precached file changes. */
export function buildVersion(dir: string, files: readonly string[]): string {
  const h = createHash('sha256');
  for (const f of files) {
    h.update(f);
    h.update('\0');
    h.update(readFileSync(join(dir, f)));
    h.update('\0');
  }
  return h.digest('hex').slice(0, 12);
}

/** Source of the service worker for a given precache list and version. */
export function renderServiceWorker(files: readonly string[], version: string): string {
  return `// Generated by scripts/sw-plugin.ts at build time. Do not edit.
'use strict';
const VERSION = ${JSON.stringify(version)};
const CACHE = 'lt26-' + VERSION;
const PREFIX = 'lt26-';
const FILES = ${JSON.stringify(files, null, 2)};
const BASE = new URL('./', self.location.href);
const PRECACHE = FILES.map((f) => new URL(f, BASE).href);
const PRECACHED = new Set(PRECACHE);
const INDEX = new URL('index.html', BASE).href;

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) => cache.addAll(PRECACHE.map((u) => new Request(u, { cache: 'reload' })))),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith(PREFIX) && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

// No skipWaiting(): a new version waits until every window of the app is closed, so a running game is
// never switched to a cache that lacks the hashed files it was loaded with.
self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== BASE.origin) return;
  url.hash = '';
  if (req.mode === 'navigate') {
    // App shell: the cached index.html references exactly the hashed files in this cache.
    event.respondWith(
      caches.open(CACHE).then((cache) =>
        cache.match(INDEX).then((hit) => hit || fetch(req)),
      ),
    );
    return;
  }
  const key = url.href.split('?')[0];
  if (!PRECACHED.has(key)) return;
  event.respondWith(
    caches.open(CACHE).then((cache) => cache.match(key).then((hit) => hit || fetch(req))),
  );
});
`;
}

/** Vite plugin that writes `<outDir>/sw.js` after the bundle (and the public folder) is on disk. */
export function serviceWorkerPlugin(): Plugin {
  let config: ResolvedConfig | undefined;
  return {
    name: 'lt26-service-worker',
    apply: 'build',
    configResolved(c) {
      config = c;
    },
    closeBundle: {
      order: 'post',
      sequential: true,
      handler() {
        if (!config) return;
        const outDir = resolve(config.root, config.build.outDir);
        const files = listBuildFiles(outDir);
        const version = buildVersion(outDir, files);
        writeFileSync(join(outDir, SW_FILENAME), renderServiceWorker(files, version));
        config.logger.info(`[lt26-sw] ${SW_FILENAME}: ${files.length} files precached, version ${version}`);
      },
    },
  };
}
